---
title: "p8105_hw1_nz2333"
author: nz2333
date: 9/28/2021
output: github_document
---

```{r}
library(tidyverse)
```

Problem 1
Creating data file

```{r problem1-1}
prbone_df=
  tibble(
    random_sample = rnorm(10),
    random_sample_logic = random_sample > 0,
    character = c("Red", "Orange", "Yellow", "Pink",
                  "Green", "Blue", "White",
                  "Brown", "Grey", "Black"),
    factor_level = factor(c("Light", "Light", "Light", "Light", 
                           "Neutral", "Neutral", "Neutral", 
                           "Dark", "Dark", "Dark"))
  )
```

Get the mean value

```{r problem1-2}
mean(pull(prbone_df, var = random_sample))
mean(pull(prbone_df, var = random_sample_logic))
mean(pull(prbone_df, var = character))
mean(pull(prbone_df, var = factor_level))
```

*Based on the results, we can get mean values for the first two variables: random_sample and random_sample_logic. But we were unable to get the mean value for character and factor_level because they are not in numeric or logical format. 

Convert to numeric

```{r problem1-3, results = "hide"}
as.numeric(pull(prbone_df, random_sample_logic))
as.numeric(pull(prbone_df, character))
as.numeric(pull(prbone_df, factor_level))
```

